# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install just dependencies needed for fuzz.py
      run: |
        pip install ruamel.yaml
        pip install pandas
        pip install numpy
        pip install sarif_om
        pip install jschema_to_python
    - name: Run fuzz.py
      run: |
        python fuzz.py
        
